[2023-12-19T23:02:22.701+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: hosp_insur_claim_fraud-v01.insert_fk_into_fact_table.insert_fk_col_in_fact_table_home_or_self_care scheduled__2023-12-01T00:00:00+00:00 [queued]>
[2023-12-19T23:02:22.723+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: hosp_insur_claim_fraud-v01.insert_fk_into_fact_table.insert_fk_col_in_fact_table_home_or_self_care scheduled__2023-12-01T00:00:00+00:00 [queued]>
[2023-12-19T23:02:22.728+0000] {taskinstance.py:1361} INFO - Starting attempt 1 of 6
[2023-12-19T23:02:22.758+0000] {taskinstance.py:1382} INFO - Executing <Task(PostgresOperator): insert_fk_col_in_fact_table_home_or_self_care> on 2023-12-01 00:00:00+00:00
[2023-12-19T23:02:22.771+0000] {standard_task_runner.py:57} INFO - Started process 3727 to run task
[2023-12-19T23:02:22.784+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'hosp_insur_claim_fraud-v01.insert_fk_into_fact_table', 'insert_fk_col_in_fact_table_home_or_self_care', 'scheduled__2023-12-01T00:00:00+00:00', '--job-id', '42', '--raw', '--subdir', 'DAGS_FOLDER/Hospital_Insurance_Claim_Fraud.py', '--cfg-path', '/tmp/tmpy_od5kwh']
[2023-12-19T23:02:22.791+0000] {standard_task_runner.py:85} INFO - Job 42: Subtask insert_fk_col_in_fact_table_home_or_self_care
[2023-12-19T23:02:22.918+0000] {task_command.py:416} INFO - Running <TaskInstance: hosp_insur_claim_fraud-v01.insert_fk_into_fact_table.insert_fk_col_in_fact_table_home_or_self_care scheduled__2023-12-01T00:00:00+00:00 [running]> on host 183042dfa495
[2023-12-19T23:02:23.037+0000] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='dunnbc22' AIRFLOW_CTX_DAG_ID='hosp_insur_claim_fraud-v01.insert_fk_into_fact_table' AIRFLOW_CTX_TASK_ID='insert_fk_col_in_fact_table_home_or_self_care' AIRFLOW_CTX_EXECUTION_DATE='2023-12-01T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2023-12-01T00:00:00+00:00'
[2023-12-19T23:02:23.039+0000] {sql.py:274} INFO - Executing: -- params: table_name, dimension_col

/*
Steps 1-3 were completed in the create_dim_table.sql 
file & associated PostgresOperator
*/


-- Step 4: Add foreign key column to fact table
ALTER TABLE hosp_insur_claim_fraud_pipeline
ADD COLUMN home_or_self_care_id INTEGER;

-- Step 4: Update foreign key column to fact table with 
-- appropriate id (that matches with dim table)
UPDATE hosp_insur_claim_fraud_pipeline
SET home_or_self_care_id = dimension_table_home_or_self_care.id
FROM dimension_table_home_or_self_care
WHERE COALESCE(hosp_insur_claim_fraud_pipeline.home_or_self_care::text, '') = COALESCE(dimension_table_home_or_self_care.home_or_self_care::text, '');
[2023-12-19T23:02:23.054+0000] {base.py:73} INFO - Using connection ID 'postgres_conn' for task execution.
[2023-12-19T23:02:23.072+0000] {base.py:73} INFO - Using connection ID 'postgres_conn' for task execution.
[2023-12-19T23:02:23.079+0000] {sql.py:418} INFO - Running statement: -- params: table_name, dimension_col

/*
Steps 1-3 were completed in the create_dim_table.sql 
file & associated PostgresOperator
*/


-- Step 4: Add foreign key column to fact table
ALTER TABLE hosp_insur_claim_fraud_pipeline
ADD COLUMN home_or_self_care_id INTEGER;

-- Step 4: Update foreign key column to fact table with 
-- appropriate id (that matches with dim table)
UPDATE hosp_insur_claim_fraud_pipeline
SET home_or_self_care_id = dimension_table_home_or_self_care.id
FROM dimension_table_home_or_self_care
WHERE COALESCE(hosp_insur_claim_fraud_pipeline.home_or_self_care::text, '') = COALESCE(dimension_table_home_or_self_care.home_or_self_care::text, '');, parameters: None
[2023-12-19T23:03:43.061+0000] {sql.py:427} INFO - Rows affected: 770347
[2023-12-19T23:03:43.079+0000] {taskinstance.py:1400} INFO - Marking task as SUCCESS. dag_id=hosp_insur_claim_fraud-v01.insert_fk_into_fact_table, task_id=insert_fk_col_in_fact_table_home_or_self_care, execution_date=20231201T000000, start_date=20231219T230222, end_date=20231219T230343
[2023-12-19T23:03:43.128+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 0
[2023-12-19T23:03:43.150+0000] {taskinstance.py:2778} INFO - 0 downstream tasks scheduled from follow-on schedule check
