[2023-12-20T01:57:56.935+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: Caravan_Insurance_Challenge_Project-v01.remove_single_value_columns scheduled__2023-12-01T00:00:00+00:00 [queued]>
[2023-12-20T01:57:56.940+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: Caravan_Insurance_Challenge_Project-v01.remove_single_value_columns scheduled__2023-12-01T00:00:00+00:00 [queued]>
[2023-12-20T01:57:56.941+0000] {taskinstance.py:1361} INFO - Starting attempt 1 of 6
[2023-12-20T01:57:56.946+0000] {taskinstance.py:1382} INFO - Executing <Task(SubDagOperator): remove_single_value_columns> on 2023-12-01 00:00:00+00:00
[2023-12-20T01:57:56.949+0000] {standard_task_runner.py:57} INFO - Started process 542 to run task
[2023-12-20T01:57:56.951+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'Caravan_Insurance_Challenge_Project-v01', 'remove_single_value_columns', 'scheduled__2023-12-01T00:00:00+00:00', '--job-id', '8', '--raw', '--subdir', 'DAGS_FOLDER/Caravan Insurance Challenge.py', '--cfg-path', '/tmp/tmp3mbann2f']
[2023-12-20T01:57:56.953+0000] {standard_task_runner.py:85} INFO - Job 8: Subtask remove_single_value_columns
[2023-12-20T01:57:56.984+0000] {task_command.py:416} INFO - Running <TaskInstance: Caravan_Insurance_Challenge_Project-v01.remove_single_value_columns scheduled__2023-12-01T00:00:00+00:00 [running]> on host 32d3fe7a7987
[2023-12-20T01:57:57.028+0000] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='dunnbc22' AIRFLOW_CTX_DAG_ID='Caravan_Insurance_Challenge_Project-v01' AIRFLOW_CTX_TASK_ID='remove_single_value_columns' AIRFLOW_CTX_EXECUTION_DATE='2023-12-01T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2023-12-01T00:00:00+00:00'
[2023-12-20T01:57:57.031+0000] {logging_mixin.py:154} WARNING - /home/***/.local/lib/python3.8/site-packages/***/utils/context.py:206 AirflowContextDeprecationWarning: Accessing 'execution_date' from the template is deprecated and will be removed in a future version. Please use 'data_interval_start' or 'logical_date' instead.
[2023-12-20T01:57:57.048+0000] {subdag.py:172} INFO - Created DagRun: scheduled__2023-12-01T00:00:00+00:00
[2023-12-20T02:12:58.020+0000] {base.py:287} INFO - Success criteria met. Exiting.
[2023-12-20T02:12:58.037+0000] {subdag.py:187} INFO - Execution finished. State is failed
[2023-12-20T02:12:58.054+0000] {taskinstance.py:1937} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 1518, in _run_raw_task
    self._execute_task_with_callbacks(context, test_mode, session=session)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 1684, in _execute_task_with_callbacks
    self.task.post_execute(context=context, result=result)  # type: ignore[union-attr]
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/subdag.py", line 190, in post_execute
    raise AirflowException(f"Expected state: SUCCESS. Actual state: {dag_run.state}")
airflow.exceptions.AirflowException: Expected state: SUCCESS. Actual state: failed
[2023-12-20T02:12:58.060+0000] {taskinstance.py:1400} INFO - Marking task as UP_FOR_RETRY. dag_id=Caravan_Insurance_Challenge_Project-v01, task_id=remove_single_value_columns, execution_date=20231201T000000, start_date=20231220T015756, end_date=20231220T021258
[2023-12-20T02:12:58.073+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 8 for task remove_single_value_columns (Expected state: SUCCESS. Actual state: failed; 542)
[2023-12-20T02:12:58.116+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2023-12-20T02:12:58.131+0000] {taskinstance.py:2778} INFO - 0 downstream tasks scheduled from follow-on schedule check
