[2023-12-21T16:52:56.816+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: Indicators_of_Heart_Disease_2022-v01.impute_missing_values_strings.impute_HIVTesting_with_mode scheduled__2023-12-01T00:00:00+00:00 [queued]>
[2023-12-21T16:52:56.834+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: Indicators_of_Heart_Disease_2022-v01.impute_missing_values_strings.impute_HIVTesting_with_mode scheduled__2023-12-01T00:00:00+00:00 [queued]>
[2023-12-21T16:52:56.849+0000] {taskinstance.py:1361} INFO - Starting attempt 1 of 6
[2023-12-21T16:52:56.881+0000] {taskinstance.py:1382} INFO - Executing <Task(PostgresOperator): impute_HIVTesting_with_mode> on 2023-12-01 00:00:00+00:00
[2023-12-21T16:52:56.891+0000] {standard_task_runner.py:57} INFO - Started process 919 to run task
[2023-12-21T16:52:56.905+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'Indicators_of_Heart_Disease_2022-v01.impute_missing_values_strings', 'impute_HIVTesting_with_mode', 'scheduled__2023-12-01T00:00:00+00:00', '--job-id', '45', '--raw', '--subdir', 'DAGS_FOLDER/Indicators_of_Heart_Disease_2022.py', '--cfg-path', '/tmp/tmp_08icu4b']
[2023-12-21T16:52:56.933+0000] {standard_task_runner.py:85} INFO - Job 45: Subtask impute_HIVTesting_with_mode
[2023-12-21T16:52:57.130+0000] {task_command.py:416} INFO - Running <TaskInstance: Indicators_of_Heart_Disease_2022-v01.impute_missing_values_strings.impute_HIVTesting_with_mode scheduled__2023-12-01T00:00:00+00:00 [running]> on host 8e01071a5eb3
[2023-12-21T16:52:57.284+0000] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='dunnbc22' AIRFLOW_CTX_DAG_ID='Indicators_of_Heart_Disease_2022-v01.impute_missing_values_strings' AIRFLOW_CTX_TASK_ID='impute_HIVTesting_with_mode' AIRFLOW_CTX_EXECUTION_DATE='2023-12-01T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2023-12-01T00:00:00+00:00'
[2023-12-21T16:52:57.287+0000] {sql.py:274} INFO - Executing: -- params: table_name, column_name

UPDATE indicators_of_heart_disease_2022_pipe
SET HIVTesting = (
    SELECT HIVTesting 
    FROM indicators_of_heart_disease_2022_pipe
    WHERE HIVTesting IS NOT NULL
    GROUP BY HIVTesting
    ORDER BY COUNT(*) DESC
    LIMIT 1
)
WHERE HIVTesting IS NULL;
[2023-12-21T16:52:57.303+0000] {base.py:73} INFO - Using connection ID 'postgres_conn' for task execution.
[2023-12-21T16:52:57.329+0000] {base.py:73} INFO - Using connection ID 'postgres_conn' for task execution.
[2023-12-21T16:52:57.347+0000] {sql.py:418} INFO - Running statement: -- params: table_name, column_name

UPDATE indicators_of_heart_disease_2022_pipe
SET HIVTesting = (
    SELECT HIVTesting 
    FROM indicators_of_heart_disease_2022_pipe
    WHERE HIVTesting IS NOT NULL
    GROUP BY HIVTesting
    ORDER BY COUNT(*) DESC
    LIMIT 1
)
WHERE HIVTesting IS NULL;, parameters: None
[2023-12-21T16:53:02.608+0000] {taskinstance.py:1937} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/providers/common/sql/operators/sql.py", line 280, in execute
    output = hook.run(
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/providers/common/sql/hooks/sql.py", line 392, in run
    self._run_command(cur, sql_statement, parameters)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/providers/common/sql/hooks/sql.py", line 423, in _run_command
    cur.execute(sql_statement)
psycopg2.errors.DeadlockDetected: deadlock detected
DETAIL:  Process 74149 waits for ShareLock on transaction 1141750; blocked by process 74142.
Process 74142 waits for ShareLock on transaction 1141758; blocked by process 74151.
Process 74151 waits for ShareLock on transaction 1141751; blocked by process 74143.
Process 74143 waits for ShareLock on transaction 1141759; blocked by process 74149.
HINT:  See server log for query details.
CONTEXT:  while rechecking updated tuple (21471,7) in relation "indicators_of_heart_disease_2022_pipe"

[2023-12-21T16:53:02.635+0000] {taskinstance.py:1400} INFO - Marking task as UP_FOR_RETRY. dag_id=Indicators_of_Heart_Disease_2022-v01.impute_missing_values_strings, task_id=impute_HIVTesting_with_mode, execution_date=20231201T000000, start_date=20231221T165256, end_date=20231221T165302
[2023-12-21T16:53:02.649+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 45 for task impute_HIVTesting_with_mode (deadlock detected
DETAIL:  Process 74149 waits for ShareLock on transaction 1141750; blocked by process 74142.
Process 74142 waits for ShareLock on transaction 1141758; blocked by process 74151.
Process 74151 waits for ShareLock on transaction 1141751; blocked by process 74143.
Process 74143 waits for ShareLock on transaction 1141759; blocked by process 74149.
HINT:  See server log for query details.
CONTEXT:  while rechecking updated tuple (21471,7) in relation "indicators_of_heart_disease_2022_pipe"
; 919)
[2023-12-21T16:53:02.688+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2023-12-21T16:53:02.719+0000] {taskinstance.py:2778} INFO - 0 downstream tasks scheduled from follow-on schedule check
